blank_issues_enabled: false
contact_links:
  - name: REChain IDE Community Support
    url: https://github.com/rechain-ai/rechain-ide/discussions
    about: Please ask and answer questions here.
  - name: REChain IDE Documentation
    url: https://rechain.ai/docs
    about: Check our documentation for help and tutorials.
  - name: Security Issues
    url: https://rechain.ai/security
    about: Please report security vulnerabilities here.